### ISSUE TITLE
Can You Added Support CustomEnchants

### ISSUE THREAD

**Issue by haKingdomsCraft** [Palente/LuckyBlock#1]
Can you Make it Support For Custom Enchants (PiggyCustomEnchants)

**Comment by Palente** [comment]
Okay, i will work on it for the future update

**Comment by JohnathenHampton** [comment]
ill add the support ill fork and make support then make a merge pull request will you accept if tested and works?

**Comment by Palente** [comment]
If its work yes no problem

**Comment by Palente** [comment]
Support added in the last commit https://github.com/Palente/LuckyBlock/commit/e290be68feb04d3e6fa8413f693447acf73d221a
