### ISSUE TITLE
fix internal server error

### ISSUE THREAD

**Issue by jhampt** [Palente/LuckyBlock#3]
fix internal server error

**Comment by Palente** [comment]
Please give more details

**Comment by jhampt** [comment]
pmmp 3.8.2 this is broken

**Comment by jhampt** [comment]
place block 19 mine it internal server error

**Comment by jhampt** [comment]
i could probably fix it but im at school rn and cant access my panel to see error

**Comment by jhampt** [comment]
![image](https://user-images.githubusercontent.com/49539815/57154719-8764b180-6da7-11e9-8e5e-b8f8800a5cbd.png)

**Comment by Bluzzi** [comment]
Hello, can you send us the content of your configuration, as well as the complete error please ?

**Comment by Bluzzi** [comment]
Do you still have the problem with the last release ? @jhampt

**Comment by jhampt** [comment]
i fixed the issue myself ill test the latest release if you want me to???

**Comment by Bluzzi** [comment]
Yes, please.

**Comment by jhampt** [comment]
okay ill do so soon im busy coding a core

**Comment by jhampt** [comment]
still gives errors

**Comment by Bluzzi** [comment]
Please open a new issue if you still get errors, but with error this faith !
