### ISSUE TITLE
PM4

### ISSUE THREAD

**Issue by GamerMJay** [Palente/LuckyBlock#7]
Hello please update to PM4 and support BedrockEconomy

**Comment by Palente** [comment]
Hello, will look at it and try to support BedrockEconomy

**Comment by GamerMJay** [comment]
Okay thanks

**Comment by Palente** [comment]
Hi!
i updated the plugin for the api 4.0.0 and with support of BedrockEconomy.
Please let me know if all is correct and work as excepted so i can close this issue
Update: https://github.com/Palente/LuckyBlock/commit/23a8fea1cce4a48b641d5b77fb08e411b259fa63

**Comment by GamerMJay** [comment]
Thanks I'll try it

**Comment by GamerMJay** [comment]
have you a phar data?

**Comment by Palente** [comment]
Yes in releases: https://github.com/Palente/LuckyBlock/releases/tag/1.2

**Comment by GamerMJay** [comment]
![Uploading Screenshot_2022-02-26-23-33-15-77_5c8300b655012b1930f2e0a7b81bf6a9.jpg…]()

**Comment by GamerMJay** [comment]
ah had to activate BedrockEconomy 😅

**Comment by GamerMJay** [comment]
So the plugin runs flawlessly. thank you for updating it
